# Generated by Django 3.1.2 on 2021-01-06 11:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastmodifiedOn', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 1, 6, 16, 43, 20, 671650))),
                ('IsActive', models.BooleanField(max_length=30)),
                ('BName', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastmodifiedOn', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 1, 6, 16, 43, 20, 671650))),
                ('IsActive', models.BooleanField(max_length=30)),
                ('MCName', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='cat_pics')),
                ('added_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastmodifiedOn', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 1, 6, 16, 43, 20, 671650))),
                ('IsActive', models.BooleanField(max_length=30)),
                ('DCName', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastmodifiedOn', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 1, 6, 16, 43, 20, 671650))),
                ('IsActive', models.BooleanField(max_length=30)),
                ('SCName', models.CharField(max_length=30, unique=True)),
                ('MC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spencersapp.category')),
                ('added_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastmodifiedOn', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 1, 6, 16, 43, 20, 671650))),
                ('IsActive', models.BooleanField(max_length=30)),
                ('pname', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_quantity', models.IntegerField(default=0)),
                ('batch_no', models.CharField(blank=True, max_length=30, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('prod_desc', models.TextField(blank=True, null=True)),
                ('mrp', models.FloatField()),
                ('total_price', models.FloatField()),
                ('landing_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('offer_perc', models.IntegerField(blank=True, default=0)),
                ('offer_type', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=30, null=True)),
                ('offer_from', models.DateField(blank=True, null=True)),
                ('offer_to', models.DateField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, upload_to='pics1')),
                ('image2', models.ImageField(blank=True, upload_to='pics2')),
                ('image3', models.ImageField(blank=True, upload_to='pics3')),
                ('image4', models.ImageField(blank=True, upload_to='pics4')),
                ('offer_price', models.FloatField()),
                ('is_offer', models.BooleanField(default=False)),
                ('Brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spencersapp.brand')),
                ('DC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spencersapp.detailcategory')),
                ('MC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spencersapp.category')),
                ('SC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spencersapp.subcategory')),
                ('added_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='detailcategory',
            name='SC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spencersapp.subcategory'),
        ),
        migrations.AddField(
            model_name='detailcategory',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='DC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spencersapp.detailcategory'),
        ),
        migrations.AddField(
            model_name='brand',
            name='SC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spencersapp.subcategory'),
        ),
        migrations.AddField(
            model_name='brand',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
