# Generated by Django 3.1.2 on 2021-01-29 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spencersapp', '0005_auto_20210129_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='authenticate',
            new_name='authenticate1',
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 17, 27, 1, 698217)),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 17, 27, 1, 698217)),
        ),
        migrations.AlterField(
            model_name='detailcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 17, 27, 1, 698217)),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 17, 27, 1, 698217)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 17, 27, 1, 698217)),
        ),
    ]
